# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b62b5df28e0493361b77c61e76c89c6dd93708dbbf18737fb322fc51dd35574b62a3e008af9ae2ae887bc52d6e93ae71b6ab7a719ac0a65d99f0c33bb19ebc5

test:
  secret_key_base: 528cd0841a9b612d5982911475abd7d70adbea145e554b621658295e8380f08ab6f4be92c7de9cb9ba1af8e2f2efad82dd01bde1c6597132a161975a372371fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
